# Generated by Django 4.2.5 on 2023-09-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={},
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table='Accounts',
        ),
    ]
