# Generated by Django 4.2.5 on 2023-09-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_options_alter_useraccount_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='accounts',
        ),
    ]
