# Generated by Django 4.2.5 on 2023-09-29 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(choices=[('FREE', 'FREE'), ('INITIAL_PLAN', 'INITIAL'), ('PROFESSIONAL_PLAN', 'PROFESSIONAL'), ('BUSINESS_PLAN', 'BUSINESS')], default='FREE', max_length=100)),
                ('subscription_id', models.CharField(max_length=150, null=True)),
                ('next_payment', models.DateTimeField(null=True)),
                ('number_projects', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
